services:
- docker
before_script:
- docker build -t tarciosaraiva/go-ui-xbuild-base base
- docker tag tarciosaraiva/go-ui-xbuild-base tarciosaraiva/go-ui-xbuild-base:${TRAVIS_BUILD_NUMBER}
script:
- docker build -t tarciosaraiva/go-ui-xbuild .
env:
  global:
    secure: RGaWc+pfqsqvBF4khcJWVfBWKC9z/9Fv7llxhRZ293YDcpU0IQAofeBHLo+G+svkxoSptQIfvnH+Bjcw85ibgRRSuGLQg0OYmSPfcVdPvuJsGLy5Vr6aILfdbukLP++bZTWgctg2kz1ypSwaa1h3fNCQzQcZ7WS77VDpLfbfv/QN7uPTvJ85j6r126rPBSRVYEHy7qxTh6IPPelbjWiMgy6BBroPZSYwUU8Qn0hFxFaK5FU1nuCoXNV6lxwoNI+y9HNx/8z7e7vLx7k0wpAKeCJiGoNsF0R7uNkFFBem6Kvxgzs26ZWxRa1twJ+ysLxihRd71ZxqvK/bdYyJnpyWFJefJ87fa+D0o/lxM+0PJqiNzVLI4UCILdVi+aWY2dRQfPYoJsEAZoqPAfazO0kR7bDKSLAyPzaKEXq3tY60DsgiKRAP7uBecYqPdWx4F8MTJ2nx0BeJeDFEHnqRPJMNr/JtayOK7B5t/gD0CTQGUS/SkS24hkikGYx4VAoAa4m1T9JymPgxli/S2Ad5iPrDXuvZu8XTzV+xVXuIj3CJgLjmmtX6S024eTyRq90O4ySe97yCn+6kAfJbusWAJYek3tE8pC0wlRM7fpeFhdPFTQoZoGMhqRmF8Q5IJpELgZBUTFIPJSKyee8zP1Bfyoew0D4GgpgnMmOqENA5egXgwBA=
