services:
- docker
script:
- docker build -t tarciosaraiva/go-ui-xbuild-base base
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push tarciosaraiva/go-ui-xbuild-base
- docker build -t tarciosaraiva/go-ui-xbuild .
- docker push tarciosaraiva/go-ui-xbuild
